---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
  namespace: vault-auth-csi
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault-test.nase.team"
    vaultCACertPath: '/mnt/tls/ca.crt'
    vaultKubernetesMountPath: 'kubernetes_csi'
    roleName: "web-app"
    objects: |
      - objectName: "db-password"
        secretPath: "kv/data/webapp/config"
        secretKey: "password"
